require: rubocop-rspec

AllCops:
  Exclude:
    - 'spec/fixtures/**/*'
  NewCops: enable

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude: 
    - spec/**/*
    
RSpec/RepeatedExampleGroupBody:
  Enabled: false

Style/Documentation:
  Enabled: false
